### ISSUE TITLE
(PT114)  --  Another request to bypass the Letter Queue for Public Records

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#302]
Clicked on the “Public Records” tab and received the REP Public Records Pop-Up Box.
Select the document to be sent.
![image](https://cloud.githubusercontent.com/assets/24595073/23778226/0eb5a132-0507-11e7-81db-28b0e63fc27f.png)

Select the document to be sent.
![image](https://cloud.githubusercontent.com/assets/24595073/23778228/15b17236-0507-11e7-9583-c81b39c0139c.png)

The Email Pop-Up Box appears.
![image](https://cloud.githubusercontent.com/assets/24595073/23778259/4e08a276-0507-11e7-8c30-aaa846059f7f.png)

Fill in information on the Public Records Email. Then click “Save.”
![image](https://cloud.githubusercontent.com/assets/24595073/23778263/55607a62-0507-11e7-8d9e-bfbcc46dfc86.png)

The document then goes to the Letter Queue. In the current system, the document does not go to the letter queue; instead, it goes directly to the recipient. Can we do away with this process for efficiency.
![image](https://cloud.githubusercontent.com/assets/24595073/23778272/5d4f97e4-0507-11e7-90e6-ddb39c3a0b23.png)

**Comment by altrdgenetics** [comment]
that was not the process as described to us in the PR meeting. It was to go to the letter queue, the only request they had was for the email window to type in their own information. We already had a request for the subject in a ticket... why was this not an issue when... but now it is.

**Comment by altrdgenetics** [comment]
Added the question label since we were told that EVERYTHING was to go to the letter queue that was going out as a double verification. Now that it is asked for to NOT go to the queue but actually auto-send.. I wanna hear the approval from SERB Management that it is an valid request....

This should not take much work to change, but I'm not moving the application to a more dangerous position prone to accidental clicking without verification from management.

**Comment by altrdgenetics** [comment]
justin approved this bypass

**Comment by altrdgenetics** [comment]
completed this and added in double checks for files existing EVERY STEP OF THE WAY
