### ISSUE TITLE
(PROD059) - multiple MED Report Tweaks

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#434]
no table of contents, just rescanned images that do not like to show up on github.

**Comment by anthonyperk** [comment]
Fact Finding Reports Received - Mail Log
-I was not looking for the new spelled out Activity (Was looking for 'IN - FF REPT', and not for 'IN Filed Fact Finding Report')
-Added 'Employer' Column
-Removed 'Email From' Column

Active Fact Finders Listing
-Currently there are no Active Fact Finders that are also Conciliators (Type O), however I have added that to the WHERE statement
I made a mistake, “O” means off the list. All conciliators are also fact finders, please replace Type “O” with type “C”
-I reduced the space between the entries by half.  page 1 holds 20 (rather than 10) and the next pages hold at least 24.  Ask Mary/Tammy if that is better.
-Bottom note says 'not in Alpa Order by First name'.  Not sure what this means.
- This means that she wants the fact finders list sorted by Fact Finder by First Name. A to Z

Active Conciliators Listing
-I reduced the space between the entries by half.  page 1 holds 20 (rather than 10) and the next pages hold at least 24.  Ask Mary/Tammy if that is better.
-I did not add the 'Type O' to the WHERE statement since it was not asked for.

Active Mediators Listing
-I reduced the space between the entries by half.  page 1 holds 18 (rather than 10) and the next pages hold at least 24.  Ask Mary/Tammy if that is better.
-State mediators group is above FMCS group
-State and FMCS will print in capital letters
-Sort within the Mediator Group by first name

Conciliator Awards Received
-Bolded the Conciliator name
-Got rid of the line between the Conciliator group
-The date that is claimed to be incorrect is actually correct from the old system
 


Case Listing Report - NTN Filings
-I reduced the space between the entries.  There is still space between the entries, but it is less than it was when you last ran it (any less space and the entries would start to run into each other)
-From what I can see, the negotiation types are correct and all there.  One case (2017-MED-02-0117) does not have a negotiation type, so this is why the count of the 6 Negotiation Types and the total Record Counts is off. 

MED Employer Case History Report
-I reduced the space between the entries.
-Negotiation Types are printing correctly.

MED Cases to be Closed by Board
-The 2.0 system DID prompt for the board meeting date, however it didn’t actually use the date in the query (it only used that date prompt to populate a field in the header).  I have added this to this report and the MED Cases to be Closed by Board(Withdrawn-Dismissed) Report.
-Moved Case Number to the far right side.
-I reduced the space between the entries.

MED Open Cases
-I reduced the space between the entries.

Monthly Stats - Conciliator Appointments
-I reduced the space between the entries.
-Swapped Conciliation Type and Conciliator Selected

Monthly Stats - Fact Finder Appointments
-I reduced the space between the entries.
-Swapped Fact Finding Type and Fact Finder Selected
-I noticed the notes about adding the related case number(s) with the actual case number.  Is it just the related case number or should it be the multi-case numbers as well?
- This should be the multi-case number field. 

Monthly Stats - Mediator Appointments
-I reduced the space between the entries.
-Craig Young to Chris Young, how far back should this be done?
-June 2013 to present
