### ISSUE TITLE
(R3-027) - (CMDS/Email Server) - Fax2Mail Attachment import issue

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#595]
In the CMDS section, when we receive a Fax2Mail email, the system will import the ebody, but it will not
import the attachment (which is actually the fax message as an attachment). If I forward the problem fax
back to the SPBR box, the system will import it correctly, as shown below highlighted in blue.

Copies of these can be found in the SPBR email box in the archive folder.
Dated 8/1/2017 from “Fax2Mail”

![image](https://user-images.githubusercontent.com/24595073/28845340-aeae7da4-76d5-11e7-810c-59d0d284e493.png)

**Comment by altrdgenetics** [comment]
I believe this will be an issue with content blocking on O365 side. I see nothing wrong with the file, it is sent as a PDF. most likely due to non-verified sender and the way the attachment is inserted into the message

![screenshot 2](https://user-images.githubusercontent.com/8847344/29380508-f30efeb4-8293-11e7-89b1-059fe6557bd7.png)

**Comment by altrdgenetics** [comment]
emailed Justin about the issue closing out the ticket.
