### ISSUE TITLE
(R3-047) - (MED) - Batch Close Report Display Issue

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#615]
In the Mediation Section (This is the first time this has been used since it was programmed)
File > Batch Handle Cases > MED
Select Send to Board. Select date Ranges below.
Press Print Board to Close List
Populate Board Date Prompt of 10/12/2017

![image](https://user-images.githubusercontent.com/8847344/30879775-71db8a0a-a2ce-11e7-914a-2c90e7568f7e.png)

You get the info below.
The report does not list any of the records.

![image](https://user-images.githubusercontent.com/8847344/30879790-785d21f4-a2ce-11e7-9876-5ebf7ad50673.png)

**Comment by anthonyperk** [comment]
EMAIL TO JUSTIN:

Justin,

The reason that the report is blank is because it queries the database for any cases that are: 
Status = Open 
--and--
‘Send to Board to Close’ box under Status = checked.

Could it be that the MED section hasn’t marked anything to be sent to the board to close before running the report?  They would have to check the cases in the ‘Send MED Cases to Board to Close’ and click update before anything will be shown on the report.  According to the code and process in 2.0, users would have to select the cases in this table and hit update before anything would be marked as ready to send to the board to close.  At that point in time, the report could be run.  Is this still the process?

**Comment by altrdgenetics** [comment]
**FROM JUSTIN:**

> XLN Team,
>  
> Please close ticket R3-047. My mistake.
>  
> Thank you,
> Justin Brown
