### ISSUE TITLE
(R3-093) - (Hearings) - Hearings calender invite always goes to Jeanette, no matter who is the ALJ

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#662]
SERB Hearing Section

When Ray or Justin Schedule a SERB Hearing in case 2017-REP-09-0116, The ALJ appears correct below within SMDS but the outgoing email calendar invite always goes to Jeannette. We even tested by selecting Jim from the New Hearing Screen. We do not have very many Hearing cases and I am wondering if this is a bug that we missed.

![image](https://user-images.githubusercontent.com/24595073/42697667-c3074b7c-8689-11e8-91a8-0f6d65392570.png)

![image](https://user-images.githubusercontent.com/24595073/42697672-c5e3f304-8689-11e8-8cc6-b5625385b075.png)

![image](https://user-images.githubusercontent.com/24595073/42697677-c91b9220-8689-11e8-9c65-62b7edae9ac7.png)

**Comment by anthonyperk** [comment]
I tried to poke around to see if Jeanette's user ID was hardcoded into the panel by accident, but I didnt see anything like that

**Comment by altrdgenetics** [comment]
I need you to check on something. Upon checking through the code and the email server I do not see that Jeanette being coded in anything or anywhere. No code exists that puts her name into the calendar invite. I generated a hearing invite for a REP case and walked through the code and checked the database. Her name isn't on anything and no user is hard coded on the email server side. The generated invite can be seen on our DB in EmailOutInvites. I do not believe this is a code related issue and I need you to verify my theory with Justin:

So I think the root cause is the way that their mailbox system works and Office Outlook. Looking at the screenshot provided I do not see Jennette listed anywhere, I do however see "REP@SERB.state.oh.us" listed on both the email and the calendar invite. Because the cal invite was sent from "REP@" it is being deemed the organizer of the event and will auto add it to any calendar that has that account plugged into it. IT just so happens that Jennette has the REP email attached to her outlook. I am guessing anyone that adds that trunk email address will also have the same issue. 

For context Hearings section will attach the origin section email account as its outbound account settings. REP hearings from from REP@, ULP from ULP@, etc.

**Comment by anthonyperk** [comment]
EMAIL TO JUSTIN

> In regard to R3-093:

> 
> We see that in the example in the ticket, Jennette’s name doesn’t appear anywhere in the invite.  We also stepped through the code and Jennette isn’t hard coded to anything within the process.  The only address that is used is the ‘REP@SERB.state.oh.us’ address.  Is it possible that Jennette has the ‘REP@’ address either automatically sent to her OR has that address configured on her outlook (and with that, since the REP email address is the organizer of the calendar invite, it automatically adds it to Jennette’s calendar)?  Either that, or something within the email account in exchange is automatically adding Jennette to the invite.
> 
> Can you take a look at that for us?



EMAIL FROM JUSTIN

> Anthony, 
> 
> I disabled the email sending program and tested again. In Case 2017-REP-09-0116 I created two new hearings. I selected Ray for the first and Jim as the ALJ for the second hearing. I also selected different hearing rooms. In both examples it adds Jeannette’s email address to the cases in the outgoing invites in SMDS
> 
> I then tested a different REP case and ULP case. In both of those instances it worked properly.

![image](https://user-images.githubusercontent.com/24595073/43544414-cf951628-95a0-11e8-86ce-d5e2c73f1998.png)


EMAIL FROM JUSTIN

Anthony, 

It appears that this issue is only happening in one case (2017-REP-09-0116). I am wondering if it is a null pointer file error. 

Thank you,

**Comment by anthonyperk** [comment]
looks like it is just one case that the issue is on
