### ISSUE TITLE
(R3-125) - (EMAIL) - Open File Error when sending Emails

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#722]
I have noticed an increase in the instances where the SMDS Email application is erroring out because the sender of an outgoing message still has the Word version of the document open causing an open error on the SMDS Email Server.

Can we add a verification prompt to inform the user to close the word document prior to sending?

**Comment by anthonyperk** [comment]
Justin is swinging by tomorrow (6/6/2019), I will get more info on this

**Comment by altrdgenetics** [comment]
I mean we can... but that isn't going to change anything. 

1. As we know the files stored separately from the application there is no way we can "lock" them. 
1. The sending of emails occurs independent of clicking the "send" button
1. **And most importantly we check for locked files between users hitting the send button and the email being sent... so this ISSUE is already occurring AFTER the last possible step in the process that we could even put within the application itself.**

The check on that happens in this method: [ProcessSendingEmail.java](https://github.com/CurrentlyNotSet/SERB/blob/0c61bc74363e4fdc2f8f76eeb1dee14b59d9247a/src/main/java/parker/serb/letterQueue/ProcessSendingEmail.java#L40)

Soooo.... if/when an email fails at that step it will never remove itself from the application or get the checkmark as ready to send. Which is the big hint to users that the email has a file is open. If it gets past that it is pretty much out of our control and up to users to correct their habits or tied to the network/filesystem that is managed by OIT and out of our control. Our check is to test if we can rename the file. If the OIT NAS has the multiple use/versioning enabled now then not much we can do about checking if it is in use.

We can provide better access or another way of seeing which emails are locked or awaiting the sending of email due to this problem. There is no changing how SERB employees perform their job and an additional line of text in a popup dialog will not change that.

**Comment by anthonyperk** [comment]
I am still waiting on a screen shot of the popup just so we are sure of the issue.  It seems to be sporadic, and I believe that Ray is the one that keeps causing the issue.

**Comment by anthonyperk** [comment]
Talked to Justin on 9/26.  He says this really hasn't popped up in a while, but doesn't want to close the ticket quite yet.

**Comment by altrdgenetics** [comment]
No additional complaints ticket closed due to inactivity. No additional complaints either.
