### ISSUE TITLE
2021-001 - MED - Two Strike tab dropdown fields don't actually save

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#747]
MED Section

On the Mediation > Strike Tab. Data does not save in the highlighted two fields. This fields can be linked to the existing fields FFEmployerType and FFEmployeeType that are used on the Fact Finder Tab.

![image](https://user-images.githubusercontent.com/24595073/88395641-62cf6d80-cd8f-11ea-853d-30d163459fe9.png)

**Comment by altrdgenetics** [comment]
There appears to be some copypaste related issues but it also looks like these fields are not fully referenced everywhere in the code that they should be. Were these two added after an initial showing? especially since you mentioned that they are duplicate fields.

![Screenshot (140)](https://user-images.githubusercontent.com/8847344/88467602-876a3900-cea6-11ea-9aa3-0881bbd14576.png)

**Comment by anthonyperk** [comment]
I looked through the tickets and didnt find anything about these dropdowns, so perhaps they never worked.

I am assuming that they can just be linked to those two DB fields?

**Comment by anthonyperk** [comment]
Tested and deployed to SERB

Justin confirms it functions correctly.
