### ISSUE TITLE
2021-006 - All Sections - Internal notes text box is not accessible from the activity tab

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#753]
All Sections
The internal notes text box is not accessible from the activity tab when view the case activity for the entry.

![image](https://user-images.githubusercontent.com/24595073/94162122-6006fc80-fe54-11ea-8e4f-d4f649168017.png)

![image](https://user-images.githubusercontent.com/24595073/94162144-64cbb080-fe54-11ea-98b5-1f4c7e75d729.png)

**Comment by altrdgenetics** [comment]
well we dont do anything with this at all... it only stays with the public records email. Once the email send it out... poof it is gone. Anything they had put in prior in that text area has never been saved anywhere.

**Comment by anthonyperk** [comment]
JUSTINS RESPONSE

Anthony, At one point in time, I think SMDS 2.0, The internal note was accessible via the activity entry screen. This was helpful because we could log the request in that box and then see it when clicking on the public records activity entry.

Is the internal notes stored anywhere at this time or is that field lost when the send button is pressed?

 
![image](https://user-images.githubusercontent.com/24595073/96611777-05ce4f80-12cb-11eb-9434-15cda90da8a8.png)


Activity Entry Example:
Below is an example of how this info could look. I don’t know if it is worth the programming though. Maybe the extra info only shows when the activity entry is a public records?

 
![image](https://user-images.githubusercontent.com/24595073/96611753-ffd86e80-12ca-11eb-9905-00dae4f9842d.png)

**Comment by altrdgenetics** [comment]
The activity table in the database does not contain the field for internal notes. Also checking medhistory in SERB2.0 i still dont see the internal notes. Not sure if this is something that was just supposed to be viewed before sending out the email. 

In order to add the functionality to the system we would need to add some additional logic to the email server application as well as add the field to the Activity panel on the main database and also the visuals too. I am assuming the attachments table is a typo since each activity panel only includes a single file. I would expect this to take 8hrs

**Comment by anthonyperk** [comment]
Justins Response

The internal note would not be public record, Just visible to staff.

**Comment by anthonyperk** [comment]
Ticket has been CANCELED
