### ISSUE TITLE
2021-007 - All Sections - Export Docs button on Public Records Screen 

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#754]
All Sections
On the public records screen, add an export docs button. This button allows users to export the selected files to a specified folder on PC. This allows users to upload the folder of exported files to a OneDrive account to share. This will address the issue with public records requests that are too large to email.

When exporting files append the received date (displayed on activity screen) to the beginning of the filename “2020-09-23_”. So the files can be viewed in date order This will assist the courts and others putting the files in the correct order.

![image](https://user-images.githubusercontent.com/24595073/94162333-980e3f80-fe54-11ea-9292-986d98eafb4a.png)

Also append the date on the files when sending public records requests. They currently are named the same as they are stored on the G: Drive. (Next page)

![image](https://user-images.githubusercontent.com/24595073/94162373-a2303e00-fe54-11ea-9447-e798045a00b0.png)

**Comment by altrdgenetics** [comment]
This is lacking too many details. please get more.

How are we saving them off? individual files or combinedPDF?
Where exactly are they being saved to? does what justin said mean he wants a folder selector popup?
Naming? The date alone is inadequate since it will not handle multiple public records requests on the same day.

**Comment by anthonyperk** [comment]
JUSTINS RESPONSE

Anthony, we would want to save the files off individually. We would want a folder selector popup box. 
If the date was added to the front of existing “unique entry” it would not cause any problems because the file name would still be unique. We would also want this for ticket 006 so the parties can quickly put the files in date order. If there is a max character issue, Maybe trim off the right side so it doesn’t exceed character limit. 
Example:
2020-10-16_1594049690214_Fact Finder Appointment Letter.pdf 
2020-10-16_1593532361682_Fact Finder Appointment Letter.pdf

**Comment by anthonyperk** [comment]
Justin's Response

Timestamp: I just want Year- Month-Day appended to the front so it is easily sorted. Since the emails are sent one case at a time, we do not need case number appended in file name.


This sounds like they want it exactly as the last response indicated.

**Comment by altrdgenetics** [comment]
For the Export button I expect it to be 4hrs of labor. 

The Filename is a bit more difficult. The application references and keys everything on the filename on the G:\ 

I would expect the filename change to easily add 8-14hr more to the 4hrs above to do this. This is also under the impression that the file name change on outgoing email is changed for EVERY single email type, for ALL sections. This would also cover the request for file name change on outgoing emails in 006.

If SERB is looking to target certain types of emails going out while leaving others in regular naming format it will add an unknown amount above the 8-14hr due to us needing to find something to key off of in each instance. 

Most of the time will be consumed in testing these changes to ensure that nothing is broken, pretty much everything interacts with files on the G:\ so gotta make sure everything works.

I do have some slight concerns changing the filenames in the way presented as stripping off the case number off then we will break apart the name making a raw search within Windows on the G:\ more difficult to quickly find the file. I would prefer if we could just add the date as a prefix at the beginning and not change anything else in the filename. Adding and additional 10 characters wont change too much. 


- Original: [TIMESTAMP]_[CASENUMBER]_[FILENAME].ext
- Justin: [DATE]_[TIMESTAMP]_[FILENAME].ext
- Andrew: [DATE]_[TIMESTAMP]_[CASENUMBER]_[FILENAME].ext

**Comment by altrdgenetics** [comment]
I believe for this one I am still waiting on the final decision of the filename

**Comment by anthonyperk** [comment]
Updated Ticket Request

All Sections
On the public records screen of all sections, add an export docs button. This button allows users to export
the selected files to a user specified folder on the PC. This allows users to upload the folder of exported
files to a OneDrive account to share. This will address the issue with public records requests that are too
large to email.

**Note: The files can retain their existing filename in the new folder. No rename needed.**

**Comment by anthonyperk** [comment]
Again this is going to be saved on the users PC or OneDrive so it shouldn't interfere with existing files in the G Drive

**Comment by altrdgenetics** [comment]
this is ready to be merged in based on the work as described.

**Comment by anthonyperk** [comment]
One 'issue' I did find is the Folder Explorer does not list the Desktop folder in the C:\Users\<user name>\ folder.  Does show every other folder, even hidden ones.  Weird.

**Comment by altrdgenetics** [comment]
![Screenshot (280)](https://user-images.githubusercontent.com/8847344/149440522-125793f4-6142-42a5-9d47-5dc15c8e4a13.png)

**Comment by anthonyperk** [comment]
This must just be my machine.  Closing this ticket

**Comment by anthonyperk** [comment]
Justin is requesting the functionality to auto open the saved folder location upon completion of Public Records Exports

**Comment by altrdgenetics** [comment]
this has been merged in please validate.

https://github.com/CurrentlyNotSet/SERB/pull/797/files

**Comment by anthonyperk** [comment]
Issues from Justin

1)	When the Export button is used for the public records request, the system opens the folder of the original file location after the export is completed. It should open the new file location of the exported files when the export is completed. 

2)	When I copy a case file manually from one directory on G: Drive to my desktop (same example as used above but manual), it retains the original “date Modified” of the file. The way the exporter is currently coded, SMDS gives the newly created “copied” file a new creation date of when the files were exported. Would it be possible to keep the original “date modified” date? This would be very helpful for Shane and Erin.

**Comment by altrdgenetics** [comment]
this was the PR for the fix on the last comment 

https://github.com/CurrentlyNotSet/SERB/pull/814
