### ISSUE TITLE
2021-016 - Hearings - Multiple ALJ Notifications

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#768]
Hearing Section:
In the SERB Hearing section, the ALJs get an email notification when a new entry is added to a case. The issue is that there is more than one email notification sent when the docket is processed. It does not match the number of entries, or the number of items docketed.

Example:
Case 2020-ULP-10-0205.
Two emails docketed (with one attachment each)
![image](https://user-images.githubusercontent.com/24595073/122073625-8f84dd00-cdc6-11eb-81ea-fc27a0bd7400.png)

Ray received 6 email notifications
![image](https://user-images.githubusercontent.com/24595073/122073642-94e22780-cdc6-11eb-8398-d1a884023160.png)

At first I thought this might have something to do with there being related cases (which there were two). I did a second test by sending two more emails (1 with 1 attachment, the second with 2 attachments)

My theory did not hold up. Eight email notifications were received. Based upon my logic I would have expected 9 email notifications. (1 for each email attachment(qty3) x 3 cases)

Solution: We are seeking 1 email notification each case number that was entered in the docket screen regardless of the number of attachments.

**Comment by altrdgenetics** [comment]
I request a "flow" to recreate this issue. Does this also occur with Media/Scan types?

**Comment by anthonyperk** [comment]
QUESTION TO JUSTIN

>2021-016:  Would you like the notification for just emails that are docketed, or also scans and media?  Again, its just 1 email per case number, NOT 1 email per file attachment in the case number that was just entered.

ANSWER FROM JUSTIN

>1 email notification per docket regardless of type of media (includes email, scan, and media) If multi-case, one email for each of the case numbers in the multi-case group.

**Comment by altrdgenetics** [comment]
That would be possible and much easier. It reads like it was written for security reasons but ya we could add text to it.

HOWEVER....  based on the text provided and the location and the way Hearings section works we would not be able to separate them out it would have to be for all docket notification emails. I'll wait to dig further but initial looks like it will only be a couple hours tops for adding the additional text in all the necessary places

![Screenshot (132)](https://user-images.githubusercontent.com/8847344/131197875-e8369825-5726-471c-9f48-84f9f2c4bbba.png)

**Comment by anthonyperk** [comment]
RESPONSE FROM JUSTIN

> Please proceed with quoting this for “all” notifications.

**Comment by altrdgenetics** [comment]
Quote: 3hrs

>This is still 3 steps removed from the body description of the email. Will have to do a bit of carrying of that body string to get it to the body of the ALJ notification. I am just glad that we do have a "body" for the notification in the database. Otherwise it would be more hours.

**Comment by altrdgenetics** [comment]
I believe I found some instances in which the random extra notification were being sent. This is now being removed and the descriptions should be sent in.

Please test and confirm with Justin that this format is acceptable.

**Comment by anthonyperk** [comment]
At this time I dont currently have the ability to test this out, so I will make a note for Justin to test this BEFORE replacing the current application.

**Comment by anthonyperk** [comment]
EMAIL FROM JUSTIN



In ticket 2021-016, The ALJs do receive the notifications in the current live build (without the added detail). 

When docketing in the new build, no notifications arrive when docketing using the new build, to the same case. 

I worked with one of Jim’s cases that he had received a message from yesterday (from the live version).

**Comment by altrdgenetics** [comment]
I am still waiting on a case for this to use as an example so I can trace it through the application

**Comment by anthonyperk** [comment]
Justin says we can test with live data on case 2021-REM-04-0041.

You can teamviewer into the SERB machine with these credentials:
777 740 617
7qiq2qnc

If you need my info:
Username:  36771612
Password:  xlnP@$$w0rd!!!!

**Comment by anthonyperk** [comment]
EMAIL FROM JUSTIN

We tested with live case 2021-REM-04-0041, which is assigned to Jim. 

I used this case because he did receive the message from the current build of SMDS, just not the new build. Since we are just docketing test docs to the case, there won't be any issues testing with it. 

I can get Jim’s  login credentials to view his emails via webmail to see if the message comes through.

**Comment by altrdgenetics** [comment]
Spent time finding it. The old version is sending emails upon validating the case numbers

https://github.com/CurrentlyNotSet/SERB/blob/f0b3f0f152b16c9dd133591695df977ba8e55796/src/main/java/parker/serb/docket/scanCMDSFileDialog.java#L259

**Comment by anthonyperk** [comment]
Update from JUSTIN


Anthony, 

Thanks for the update! 

This has turned into a task!   

Questions

1)	If we undo the change, so the activity entry description is not appended to the email, does that get the prompt working again?
2)	Has this been an issue with inconsistent sending that we just now discovered?
3)	I am communicating with staff to identify the pros/cons and best path forward.

**Comment by altrdgenetics** [comment]
UPDATE:

This will take 3 additional hours to fix but I do now have the fix for the original ticket question... this additional time would have been the same amount for all of it. Previous work on the ticket was not overwritten by this latest fix.

--------------------------
What has been found and needed fixed.....
--------------------------

- Docket notification object to be created to track all necessary information during the docketing process

- Conversion of the 'verify case' logic in each docket window type to be converted to return that notification object, 6 windows in total (email, media, scan [CMDS and SMDS variants for each type]). 

- Adding the notification object to the end of the logic after the user has pressed the submit button and to use the case number text box (in case of multiple case number filing to the same ALJ).

- Remove the nested notifications during the file placement process. This occurred for scanned documents and email attachments only. This was part of the multiple notification issue originally described.

-----------------------
Limitations of this fix & additional uncoverings
-----------------------

- The ALJ will no longer receive notifications for each email attachment within an email per email docketed. Only one notification will be sent per email with no additional details other than text along the lines of "An Email has been documented to the case". This is a dynamically generated field and additional work can be requested to collect the Attachment names and customize the formatting of the notification to SERBs request. A change like that requires looping through the attachment table and collecting specific attachments based on whether the document is to be saved or not.

- If the person docketing an item changes the "TO" field to anyone else other than the ALJ automatically picked no notification will be sent to that User nor will the ALJ be notified. The only way the ALJ will be notified is if the ALJ automatically selected is the same one in the TO field when submit is pressed.

- REP: original/current logic chooses "current owner" and then picks "ALJ" in its auto selection. System only notifies on ALJ and not Current owner. _This might be a question to verify with SERB but I would think current owner is always set regardless of an ALJ being assigned meaning no ALJ has ever received a REP notification._

- ULP: original/current logic is to pick the ALJ first and give notification. If there is no ALJ it falls back to "investigator", investigator does not get a notification. _This sounds correct to me but if you are checking about REP here is the information for ULP in case they ask_

**Comment by anthonyperk** [comment]
Additional request for this ticket:

I found that the ALJ email is displaying the Category drop down text instead of the Description drop-down text. Also, the comment field is omitted. Hopefully, this is a quick tweak of the code.

**Comment by anthonyperk** [comment]
Email Text currently:
"
New Documents have been filed for 2022-FRN-05-0064.

IN - Docketed Email

"

**Comment by anthonyperk** [comment]
This is all dependent on program side (SMDS vs CMDS) or even down to individual sections in SMDS.  So how much does he want to spend on this and what are the rules for each side/section

**Comment by anthonyperk** [comment]
Hearing Section:
In the SERB Hearing section, the ALJs get an email notification when a new entry is added to a case. We are seeking that the email notification contain additional information so the ALJ knows specifically what entry the email is referencing for both SERB and SPBR cases.

We are seeking 1 email notification for each case number that was entered in the docket screen (Email, Scan, Media) regardless of the number of attachments.

If the email notification can include a list of the new activity entries that would be helpful.

For CMDS, we need the description and comments for each document.

![image](https://user-images.githubusercontent.com/24595073/174095930-4bda359f-af76-4330-9604-b54e902d7afe.png)

For SERB we need the type and comment.

![image](https://user-images.githubusercontent.com/24595073/174095979-01a17cb8-8493-4271-a926-a39dd41492e2.png)

**Comment by anthonyperk** [comment]
Not sure why this isnt closed, code was already merged
